IF VALID-HANDLE({&WINDOW-NAME}) THEN DO:
    ASSIGN
        CURRENT-WINDOW                    = {&WINDOW-NAME}
        {&WINDOW-NAME}:KEEP-FRAME-Z-ORDER = YES
        THIS-PROCEDURE:CURRENT-WINDOW     = {&WINDOW-NAME}
        .
END.